dcConsData =
	[
	{ name: "WIIU.gif", keywords: ["WIIU","wii u"], tags: ["닌텐도"] },
	{ name: "닌다!닌다!.png", keywords: ["닌다!닌다!"], tags: ["닌텐도"] },
	{ name: "시게루목.gif", keywords: ["시게루목"], tags: ["닌텐도"] },
	{ name: "닌다각1.png", keywords: ["닌다각1"], tags: ["닌텐도"] },
	{ name: "닌다각2.png", keywords: ["닌다각2"], tags: ["닌텐도"] },
	{ name: "닌다각3.png", keywords: ["닌다각3"], tags: ["닌텐도"] },
	{ name: "닌다각4.png", keywords: ["닌다각4"], tags: ["닌텐도"] },
	{ name: "왜닌다안함.png", keywords: ["왜닌다안함"], tags: ["닌텐도"] },
	{ name: "엎어.gif", keywords: ["엎어"], tags: ["닌텐도"] },
	{ name: "역시암즈.png", keywords: ["역시암즈"], tags: ["닌텐도"] },
	{ name: "이건된다.gif", keywords: ["이건된다"], tags: ["닌텐도"] },
	{ name: "니들사라고.gif", keywords: ["니들사라고","니들 사라고 만든거 아니라고요"], tags: ["닌텐도"] },
	{ name: "절하십쇼.gif", keywords: ["절하십쇼", "절 하십시오"], tags: ["닌텐도"] },
	{ name: "닌텐도주식떡상.png", keywords: ["닌텐도주식떡상"], tags: ["닌텐도"] },
	{ name: "닌텐도주식떡락.png", keywords: ["닌텐도주식떡락"], tags: ["닌텐도"] },
	{ name: "사쿠라이.gif", keywords: ["사쿠라이"], tags: ["닌텐도"] },
	{ name: "갓겜.gif", keywords: ["갓겜"], tags: ["닌텐도"] },
	{ name: "고티.png", keywords: ["고티"], tags: ["닌텐도"] },
	{ name: "미정.png", keywords: ["미정"], tags: ["닌텐도"] },
	{ name: "노란놈.png", keywords: ["노란놈"], tags: ["닌텐도"] },
	{ name: "우미.gif", keywords: ["우미"], tags: ["닌텐도"] },
	{ name: "샌즈.gif", keywords: ["샌즈"], tags: ["닌텐도"] },
	{ name: "느갤로.png", keywords: ["느갤로"], tags: ["닌텐도"] },
	{ name: "구라다옹.png", keywords: ["구라다옹"], tags: ["닌텐도"] },
	{ name: "핵갸우뚱.gif", keywords: ["핵갸우뚱"], tags: ["우리핵"] },
	{ name: "핵박수.gif", keywords: ["핵박수"], tags: ["우리핵"] },
	{ name: "펀쿨섹.gif", keywords: ["펀쿨섹"], tags: ["펀쿨섹"] },
	{ name: "끄덕.gif", keywords: ["끄덕"], tags: ["펀쿨섹"] },
	{ name: "마참내.png", keywords: ["마참내"], tags: ["미리깐 달걀"] },
	{ name: "즐겁다.png", keywords: ["즐겁다"], tags: ["미리깐 달걀"] },
	{ name: "볼트구토.png", keywords: ["볼트구토"], tags: ["볼트보이"] },
	{ name: "볼트공중.png", keywords: ["볼트공중"], tags: ["볼트보이"] },
	{ name: "버그.gif", keywords: ["버그"], tags: ["BB"] },
	{ name: "의도된.gif", keywords: ["의도된"], tags: ["BB"] },
	{ name: "성능.png", keywords: ["성능"], tags: ["둘리"] },
	{ name: "야이.png", keywords: ["야이"], tags: ["둘리"] },
	{ name: "선넘네.png", keywords: ["선넘네"], tags: ["둘리"] },
	{ name: "좋지.png", keywords: ["좋지"], tags: ["둘리"] },
	{ name: "겉바속촉.gif", keywords: ["겉바속촉", "가로쉬"], tags: ["와우"] },
	{ name: "배박.png", keywords: ["배박"], tags: ["칸코레"] },
	{ name: "캐스터절규.gif", keywords: ["캐스터절규"], tags: ["페이트"] },
	{ name: "일본택시.gif", keywords: ["일본택시"], tags: ["일본택시"] },
	{ name: "구아악고양이.gif", keywords: ["구아악고양이"], tags: ["고양이"] },
	{ name: "눈물고양이1.gif", keywords: ["눈물고양이1"], tags: ["고양이"] },
	{ name: "눈물고양이2.png", keywords: ["눈물고양이2"], tags: ["고양이"] },
	{ name: "절규고양이.png", keywords: ["절규고양이"], tags: ["고양이"] },
	{ name: "군침고양이.png", keywords: ["군침고양이"], tags: ["고양이"] },
	{ name: "우웩고양이.gif", keywords: ["우웩고양이"], tags: ["고양이"] },
	{ name: "총고양이.gif", keywords: ["총고양이"], tags: ["고양이"] },
	{ name: "따봉고양이.png", keywords: ["따봉고양이"], tags: ["고양이"] },
	{ name: "파멸고양이.gif", keywords: ["파멸고양이"], tags: ["고양이"] },
	{ name: "페페웃음.png", keywords: ["페페웃음"], tags: ["페페"] },
	{ name: "페페절규.png", keywords: ["페페절규"], tags: ["페페"] },
	{ name: "페페총.png", keywords: ["페페총"], tags: ["페페"] },
	{ name: "페페입.gif", keywords: ["페페입"], tags: ["페페"] },
	{ name: "페페팔.gif", keywords: ["페페팔"], tags: ["페페"] },
	{ name: "페페주먹.gif", keywords: ["페페주먹"], tags: ["페페"] },
	{ name: "페페팝콘.gif", keywords: ["페페팝콘"], tags: ["페페"] },
	{ name: "심영웃음.png", keywords: ["심영웃음"], tags: ["심영"] },
	{ name: "심영놀람.gif", keywords: ["심영놀람"], tags: ["심영"] },
	{ name: "심영폭발.gif", keywords: ["심영폭발"], tags: ["심영"] },
	{ name: "심영절규1.gif", keywords: ["심영절규1"], tags: ["심영"] },
	{ name: "심영절규2.gif", keywords: ["심영절규2"], tags: ["심영"] },
	{ name: "김두한웃음.gif", keywords: ["김두한웃음"], tags: ["심영"] },
	{ name: "나만아니면돼.gif", keywords: ["나만아니면돼"], tags: ["호동"] },
	{ name: "호동환호.gif", keywords: ["호동환호"], tags: ["호동"] },
	{ name: "흠1.gif", keywords: ["흠1"], tags: ["흠터레스팅"] },
	{ name: "흠2.gif", keywords: ["흠2"], tags: ["흠터레스팅"] },
	{ name: "흠3.gif", keywords: ["흠3"], tags: ["흠터레스팅"] },
	{ name: "이승윤의문.png", keywords: ["이승윤의문"], tags: ["이승윤"] },
	{ name: "이승윤박수.gif", keywords: ["이승윤박수"], tags: ["이승윤"] },
	{ name: "문풍당당.gif", keywords: ["문풍당당"], tags: ["문이과"] },
	{ name: "이풍당당.gif", keywords: ["이풍당당"], tags: ["문이과"] },
	{ name: "행복회로.gif", keywords: ["행복회로"], tags: ["행복회로"] },
	{ name: "광기.png", keywords: ["광기"], tags: ["다키스트던전"] },
	{ name: "AMD.png", keywords: ["AMD"], tags: ["AMD"] },
	{ name: "RYZEN.png", keywords: ["RYZEN"], tags: ["AMD"] },
	{ name: "나라걱정.png", keywords: ["나라걱정"], tags: ["삼국지"] },
	{ name: "그런건없다.png", keywords: ["그런건없다"], tags: ["삼국지"] },
	{ name: "요시땀.gif", keywords: ["요시땀"], tags: ["요시"] },
	{ name: "요시눈물.gif", keywords: ["요시눈물"], tags: ["요시"] },
	{ name: "웨이브앵무.gif", keywords: ["웨이브앵무"], tags: ["앵무"] },
	{ name: "팝콘앵무.gif", keywords: ["팝콘앵무"], tags: ["앵무"] },
	{ name: "순환앵무.gif", keywords: ["순환앵무"], tags: ["앵무"] },
	{ name: "와인앵무.gif", keywords: ["와인앵무"], tags: ["앵무"] },
	{ name: "따봉앵무.gif", keywords: ["따봉앵무"], tags: ["앵무"] },
	{ name: "눈물앵무.gif", keywords: ["눈물앵무"], tags: ["앵무"] },
	{ name: "RGB해골.gif", keywords: ["RGB해골"], tags: ["우효해골"] },
	{ name: "고속해골.gif", keywords: ["고속해골"], tags: ["우효해골"] },
	{ name: "우효해골.gif", keywords: ["우효해골"], tags: ["우효해골"] },
];