dcConsData =
	[
	{name:"겉바속촉.gif", keywords:["겉바속촉", "가로쉬"],	tags:["와우", "헬스크림"]},
	{ name: "WIIU.gif", keywords: ["WIIU","wii u"], tags: ["wii u", "갓유", "똥유", "망유"] },
	{ name: "닌다!닌다!.png", keywords: ["닌다!닌다!"], tags: ["닌다", "원숭이"] },
	{ name: "배박.png", keywords: ["배박"], tags: ["그 게임", "칸코레"] },
	{ name: "시게루목.gif", keywords: ["시게루목"], tags: ["미야모토 시게루", "농락"] },
	{ name: "닌다각.png", keywords: ["닌다각"], tags: ["닌다각", "원숭이"] },
	{ name: "엎어.gif", keywords: ["엎어"], tags: ["미야모토 시게루", "밥상 뒤집기"] },
	{ name: "역시암즈.png", keywords: ["역시암즈"], tags: ["암즈", "파란놈"] },
	{ name: "이건된다.gif", keywords: ["이건된다"], tags: ["가능", "야마우치 히로시"] },
	{ name: "캐스터절규.gif", keywords: ["캐스터절규"], tags: ["페이트", "-달-"] },
	{ name: "니들사라고.gif", keywords: ["니들사라고","니들 사라고 만든거 아니라고요"], tags: ["니들 사라고 만든거 아니라고요", "코이즈미"] },
	{ name: "절하십쇼.gif", keywords: ["절하십쇼", "절 하십시오"], tags: ["아오누마", "절하십시오"] },
	{ name: "버그.gif", keywords: ["버그"], tags: ["대부분은 버그입니다", "BB"] },
	{ name: "의도된.gif", keywords: ["의도된"], tags: ["의도된것입니다", "BB"] },
	{ name: "핵갸우뚱.gif", keywords: ["핵갸우뚱"], tags: ["우리핵", "김정은"] },
	{ name: "펀쿨섹.gif", keywords: ["펀쿨섹"], tags: ["펀쿨섹"] },
	{ name: "끄덕.gif", keywords: ["끄덕"], tags: ["그것이 약속이니까", "펀쿨색"] },
	{ name: "핵박수.gif", keywords: ["핵박수"], tags: ["우리핵", "박수"] },
	{ name: "성능.png", keywords: ["성능"], tags: ["둘리", "성능 확실하구만"] },
	{ name: "야이.png", keywords: ["야이"], tags: ["둘리", "야이 ㅅㅂ"] },
	{ name: "선넘네.png", keywords: ["선넘네"], tags: ["둘리", "선넘네"] },
	{ name: "좋지.png", keywords: ["좋지"], tags: ["둘리", "좋지"] },
	{ name: "마참내.png", keywords: ["마참내"], tags: ["미리깐 달걀", "마참내!"] },
	{ name: "즐겁다.png", keywords: ["즐겁다"], tags: ["미리깐 달걀", "즐겁다"] },
	{ name: "볼트구토.png", keywords: ["볼트구토"], tags: ["폴아웃", "볼트보이"] },
	{ name: "볼트공중.png", keywords: ["볼트공중"], tags: ["폴아웃", "볼트보이"] },
	{ name: "일본택시.gif", keywords: ["일본택시"], tags: ["일본택시", "일본 대단해"] },
	{ name: "껄룩.gif", keywords: ["껄룩"], tags: ["슬픈 고양이", "떼껄룩"] },
];